version: '3'
services:
  db:
    image: circleci/mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  wp:
    build: .
    depends_on:
      - db
    environment:
      TMPDIR: /tmp