version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
        environment:
          TMPDIR: /tmp
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          
    steps:
      - checkout
      - run:
          name: Prepare Environment
          command: |
            sudo touch /usr/local/etc/php/php.ini
            echo "memory_limit = -1" | sudo tee -a /usr/local/etc/php/php.ini
            echo "display_startup_errors = On" | sudo tee -a /usr/local/etc/php/php.ini
            echo "xdebug.force_display_errors = On" | sudo tee -a /usr/local/etc/php/php.ini
            echo "error_reporting = E_ALL ^ E_DEPRECATED" | sudo tee -a /usr/local/etc/php/php.ini
            echo "xdebug.force_error_reporting = E_ALL ^ E_DEPRECATED" | sudo tee -a /usr/local/etc/php/php.ini
            echo "detect_unicode = Off" | sudo tee -a /usr/local/etc/php/php.ini
            sudo docker-php-ext-install mysqli
            sudo apt-get update
            sudo apt-get install -y subversion mysql-client
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - run:
          name: Formatting and Compatibility
          command: |
            composer phpcbf
            composer phpcbf-tests
            composer phpcs-tests
            composer compat
      - run:
          name: Wait for DB
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      - run:
          name: PHPUnit for default PHP version on latest WP
          command: composer test-ci
      - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

